name: IAM Audit

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Lint Checks
        run: |
          pip install flake8
          flake8 .

      - name: Run Unit Tests
        run: |
          pip install pytest
          pytest --maxfail=1 --disable-warnings -q

      - name: Run IAM Audit (Simulated Forgerock)
        run: python iam_audit.py --provider forgerock

      - name: Check for Critical Issues
        run: |
          if grep -q "Critical" reports/iam_report_*.txt; then
            echo "Critical issues found! Please review the report.";
          else
            echo "No critical issues found.";
          fi

      - name: Upload Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: audit-report
          path: reports/
