name: IAM Audit

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC

jobs:
  audit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        provider: [ forgerock, aws ]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Code Linter
        run: |
          pip install flake8
          flake8 .

      - name: Run IAM Audit for ${{ matrix.provider }}
        run: python iam_audit.py --provider ${{ matrix.provider }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        # Only run AWS audit if credentials are set, otherwise always run simulated forgerock
        if: ${{ matrix.provider != 'aws' || (secrets.AWS_ACCESS_KEY_ID && secrets.AWS_SECRET_ACCESS_KEY && secrets.AWS_DEFAULT_REGION) }}

      - name: Rename Audit Report to Static File
        run: |
          # If a report file matching the pattern exists, remove any existing static report and rename it.
          if ls reports/iam_report_*.txt 1> /dev/null 2>&1; then
            rm -f reports/iam_report.txt
            mv reports/iam_report_*.txt reports/iam_report.txt
          else
            echo "No dynamic report found to rename."
          fi

      - name: Upload Report Artifact
        uses: actions/upload-artifact@v3
        with:
          name: audit-report-${{ matrix.provider }}
          path: reports/iam_report.txt
